language: java

sudo: required

before_install:
  - chmod +x gradlew
deploy:
  provider: pages
  skip_cleanup: true
  github_token: b443799065b6b8a7dade41a289e0caa288c45232
  keep_history: true
  on:
    branch: master
sccript: ./gradlew build

