language: java

sudo: required

before_install:
  - chmod +x gradlew
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 07cc473ec6fade7df2be288a061ecbcfd5c6a336
  keep_history: true
  on:
    branch: master
sccript: ./gradlew build

