language: java

sudo: required

before_install:
  - chmod +x gradlew
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 1d7242f81c34df3589d1b714c6fa123105ffdc2a
  keep_history: true
  on:
    branch: master
sccript: ./gradlew build

